version: "3.1"
services:
  mongo:
    image: mongo:3.6
    ports:
      - "27017:27017"
    volumes:
      - mongo:/data/db
  virtool:
    image: ghcr.io/virtool/virtool:v4.4.0-beta.1
    environment:
      VT_DATA_PATH: "/data"
      VT_HOST: "0.0.0.0"
    ports:
      - "9950:9950"
    volumes:
      - virtool:/data
volumes:
  mongo:
  virtool:
